config du template
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode pull request #1
Opened 2023-12-12 16:01 UTC by vinz-DY

2023-12-12 16:05 UTC, MaximeG971 approved these changes

2023-12-13 11:21 UTC, jujuck requested changes

2023-12-13 11:21 UTC, jujuck commented on frontend/.eslintrc.json
> +    "react/prop-types": "off",
On garde

2023-12-15 08:08 UTC, MaximeG971 submitted a review, later dismissed

2023-12-15 08:16 UTC, jujuck requested changes

2023-12-15 08:16 UTC, jujuck commented on backend/database/schema.sql
> +INSERT INTO terminal(city,adresseStation,xlongitude,ylatitude,power,acces_recharge,access,localisation,region, connectic_id, state_id) VALUES ('Parking Quintaou','1 allée de Quintaou, Anglet',-1.5127
Les insertions sont à faire dans le seed.js. Par convention, on sépare le schéma de la data

2023-12-15 08:16 UTC, jujuck commented on backend/src/controllers/userControllers.js
Pas de fichier inutile

2023-12-15 08:16 UTC, jujuck commented on backend/src/models/userManager.js
Pas de fichier inutile (vide)

2023-12-19 08:34 UTC, MaximeG971 approved these changes

2023-12-19 09:56 UTC, jujuck approved these changes

2023-12-19 09:56 UTC, merged