Inscription feature
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode pull request #17
Opened 2024-01-10 15:48 UTC by YounesSefiani

2024-01-11 15:33 UTC, MaximeG971 requested changes

2024-01-11 15:33 UTC, MaximeG971 commented on backend/src/controllers/userControllers.js
> +    res.json(users);
res.status(200).json(users) à la place

2024-01-11 15:33 UTC, MaximeG971 commented on backend/src/controllers/userControllers.js
> +    if (user == null) {
if (user.length === 0)

2024-01-11 15:33 UTC, MaximeG971 commented on backend/src/controllers/userControllers.js
> +      res.json(user);
res.status(200).json(user)

2024-01-11 15:33 UTC, MaximeG971 commented on backend/src/router.js
> -const profilControllers = require("./controllers/profilControllers");
il faut remettre cette ligne

2024-01-11 15:33 UTC, MaximeG971 commented on frontend/src/components/Inscription.jsx
> +/*import connexion from "../services/connexion";*/
supprimer le code mort

2024-01-11 15:33 UTC, MaximeG971 commented on frontend/src/components/Inscription.jsx
> +      alert("Les mots de passe ne correspondent pas !");
pas d'alerte, peut-être une popup toastify à la place ?

2024-01-11 15:33 UTC, MaximeG971 commented on frontend/src/components/Inscription.jsx
> +      // eslint-disable-next-line no-useless-return
supprimer tous les commentaires eslint

2024-01-11 15:33 UTC, MaximeG971 commented on frontend/src/components/InscriptionProfile.jsx
> +// eslint-disable-next-line spaced-comment
supprimer les commentaires eslint

2024-01-11 15:33 UTC, MaximeG971 commented on frontend/src/components/InscriptionProfile.jsx
> +      alert("Vous devez avoir 18 ans ou plus pour vous inscrire !");
toastify à la place ?

2024-01-11 15:33 UTC, MaximeG971 commented on frontend/src/components/InscriptionProfile.jsx
> +      // eslint-disable-next-line no-restricted-syntax
supprimer le commentaire et remplacer console.log par un console.info

2024-01-11 15:33 UTC, MaximeG971 commented on frontend/src/components/InscriptionProfile.jsx
> +      // eslint-disable-next-line no-alert
pop-up toastify ?

2024-01-11 16:27 UTC, YounesSefiani commented on backend/src/controllers/userControllers.js
> +    res.json(users);
Fait !

2024-01-11 16:28 UTC, YounesSefiani commented on backend/src/controllers/userControllers.js
> +    if (user == null) {
Fait

2024-01-11 16:29 UTC, YounesSefiani commented on backend/src/controllers/userControllers.js
> +      res.json(user);
Fait

2024-01-12 08:50 UTC, YounesSefiani commented on frontend/src/components/Inscription.jsx
> +/*import connexion from "../services/connexion";*/
Fait

2024-01-12 08:52 UTC, YounesSefiani commented on frontend/src/components/Inscription.jsx
> +      // eslint-disable-next-line no-useless-return
Fait

2024-01-12 08:52 UTC, YounesSefiani commented on frontend/src/components/InscriptionProfile.jsx
> +// eslint-disable-next-line spaced-comment
Fait

2024-01-12 09:45 UTC, YounesSefiani commented on frontend/src/components/InscriptionProfile.jsx
> +      // eslint-disable-next-line no-alert
Fait

2024-01-12 09:58 UTC, MaximeG971 requested changes

2024-01-12 09:58 UTC, MaximeG971 commented on frontend/src/components/InscriptionProfile.jsx
> +import "react-toastify/dist/ReactToastify.css";
mettre les imports css en dernier, juste en dessous de l'import de l'image

2024-01-12 10:13 UTC, MaximeG971 approved these changes

2024-01-12 10:29 UTC, MaximeG971 requested changes

2024-01-12 10:29 UTC, MaximeG971 commented on backend/src/controllers/userControllers.js
> +/* eslint-disable no-restricted-syntax */
commentaire à supprimer

2024-01-12 10:29 UTC, MaximeG971 commented on backend/src/controllers/userControllers.js
> +    console.log(hashPassword);
pas de console.log

2024-01-12 10:31 UTC, YounesSefiani commented on backend/src/controllers/userControllers.js
> +/* eslint-disable no-restricted-syntax */
Fait

2024-01-12 10:31 UTC, YounesSefiani commented on backend/src/controllers/userControllers.js
> +    console.log(hashPassword);
Fait

2024-01-12 10:32 UTC, MaximeG971 approved these changes

2024-01-12 10:45 UTC, jujuck requested changes

2024-01-12 10:45 UTC, jujuck commented on backend/src/controllers/userControllers.js
> +    console.log(hashPassword);
Quoi, un console.log ????

2024-01-12 10:45 UTC, jujuck commented on frontend/src/main.jsx
> +import Inscription from "./components/Inscription";
Ceci n'est pas un composant mais une page

2024-01-12 10:45 UTC, jujuck commented on frontend/src/main.jsx
> +    path: "/inscription_profil",
url avec un tiret

2024-01-12 10:45 UTC, jujuck commented on frontend/src/components/Inscription.jsx
> +          <header className="inscriptionHeader">
Fait un composant

2024-01-12 10:45 UTC, jujuck commented on backend/src/router.js
> +// Route to get a list of items
Nettoyage des routes, methode de controllers et manager (mise en comment)

2024-01-12 11:18 UTC, MaximeG971 requested changes

2024-01-12 11:18 UTC, MaximeG971 commented on frontend/src/pages/Inscription.jsx
> +import HeaderInscription from "../components/HeaderInscription";
import du component avant le css

2024-01-12 13:55 UTC, MaximeG971 submitted a review, later dismissed

2024-01-12 14:05 UTC, MaximeG971 approved these changes

2024-01-15 10:52 UTC, jujuck submitted a review, later dismissed

2024-01-15 10:52 UTC, jujuck commented on backend/src/validators/validateUser.js
> +  mail: Joi.string().min(5).max(50).required(),
Peut être vérifier si cela est une email.. string().email()

2024-01-15 10:52 UTC, jujuck commented on frontend/src/pages/Inscription_Profile.jsx
> +    try {
Pourquoi le bloc fait il doublon ?

2024-01-15 10:52 UTC, jujuck commented on backend/src/services/hash.js
> +    console.info(err);
Mettre un console.error (C'est une erreur)

2024-01-22 15:59 UTC, MaximeG971 submitted a review, later dismissed

2024-01-22 16:05 UTC, aimach commented on backend/src/controllers/userControllers.js
> +    res.status(201).json("OK");
possible de renvoyer juste le status avec res.sendStatus(201)

2024-01-22 16:17 UTC, aimach requested changes

2024-01-22 16:17 UTC, aimach commented on frontend/src/pages/Inscription.jsx
> +      showToastErrorMessage(user.passwordConfirmation);
il n'y a pas de paramètre dans la définition de ta fonction donc pas besoin de lui passer d'argument !

2024-01-22 16:17 UTC, aimach commented on frontend/src/pages/Inscription.jsx
> +      showToastPasswordMessage(user.password);
idem ⬆️

2024-01-22 16:17 UTC, aimach commented on frontend/src/pages/Inscription_Profile.jsx
> +      showToastErrorAge(profil.birthdate);
il n'y a pas de paramètre dans la définition de ta fonction donc pas besoin de lui passer d'argument !

2024-01-23 13:53 UTC, MaximeG971 approved these changes

2024-01-23 14:49 UTC, aimach approved these changes

2024-01-23 14:50 UTC, merged