Map feature
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode pull request #2
Opened 2023-12-20 15:19 UTC by MaximeG971

2023-12-20 15:23 UTC, sebastienbaquet approved these changes
ok

2023-12-20 15:29 UTC, sebastienbaquet approved these changes
ok

2023-12-20 16:24 UTC, aimach requested changes

2023-12-20 16:24 UTC, aimach commented on backend/src/controllers/terminalControllers.js
> +      res.json(terminal);
ajouter un status 200

2023-12-20 16:24 UTC, aimach commented on backend/src/controllers/terminalControllers.js
> +    if (terminal == null) {
est-ce que terminal est égal à null si la requête ne trouve rien ? ce n'est pas plutôt un tableau vide ?

2023-12-20 16:24 UTC, aimach commented on frontend/src/App.jsx
> +      <Map />
est-ce que vous souhaitez afficher la carte dans le composant App et sur la route /map ? si oui, ignorer ce commentaire

2023-12-20 16:24 UTC, aimach commented on frontend/src/components/Map/Map.jsx
> +import "leaflet/dist/leaflet.css";
regrouper les imports css

2023-12-20 16:24 UTC, aimach commented on frontend/src/components/Map/Map.jsx
> +            <Marker
faire un composant pour le Marker ! (avec passage de marker en props)

2023-12-20 16:43 UTC, jujuck requested changes

2023-12-20 16:43 UTC, jujuck commented on backend/src/models/TerminalManager.js
> +  async create(terminal) {
A commenter car non implémenter

2023-12-20 16:43 UTC, jujuck commented on backend/src/controllers/terminalControllers.js
> +const add = async (req, res, next) => {
Idem à commenter

2023-12-20 16:43 UTC, jujuck commented on backend/src/controllers/terminalControllers.js
> +      res.json(terminal);
Ajout d'un statut(200)

2023-12-20 16:43 UTC, jujuck commented on frontend/src/main.jsx
> +        .get(`${import.meta.env.VITE_BACKEND_URL}/api/terminals`)
Mettre un service de connexion tout de suite en place

2023-12-20 16:43 UTC, jujuck commented on frontend/src/components/Map/Map.jsx
> +import React from "react";
Ordre des imports

2023-12-20 16:43 UTC, jujuck commented on frontend/src/components/Map/Map.jsx
> +    <div>
La div est elle obligatoire

2023-12-21 15:37 UTC, jujuck approved these changes

2023-12-21 15:42 UTC, YounesSefiani approved these changes

2023-12-21 15:46 UTC, jujuck approved these changes

2023-12-21 15:46 UTC, merged