Formulaire profil
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode pull request #26
Opened 2024-01-25 15:25 UTC by sebastienbaquet

2024-01-25 15:37 UTC, MaximeG971 submitted a review, later dismissed

2024-01-25 16:23 UTC, aimach requested changes

2024-01-25 16:23 UTC, aimach commented on backend/database/schema.sql
> +  user_id INT NOT NUll ,
pourquoi cette modification ? laisser à NULL

2024-01-25 16:23 UTC, aimach commented on backend/src/router.js
>  router.post("/user", validateUser, userControllers.add);
si c'est un get("/users") alors ça doit être un post("/users") (ou inversement !)

2024-01-25 16:23 UTC, aimach commented on backend/src/validators/validateProfil.js
> +  name: Joi.string().min(1).max(50).required(),
pourquoi avoir changé firstname en name ? on perd en précision

2024-01-25 16:23 UTC, aimach commented on frontend/src/pages/Inscription.jsx
> +      setuserId(register.data.userId);
enlever le contexte qui n'est plus nécessaire du coup :P

2024-01-25 16:46 UTC, sebastienbaquet commented on backend/src/router.js
>  router.post("/user", validateUser, userControllers.add);
le post était déjà fait sans le s à user mais si j ajoute cela ne fonctionne plus.

2024-01-25 16:47 UTC, sebastienbaquet commented on backend/src/validators/validateProfil.js
> +  name: Joi.string().min(1).max(50).required(),
dans la data base c'etait name , j ai respecter la data .

2024-01-26 09:35 UTC, MaximeG971 approved these changes

2024-01-26 09:45 UTC, aimach approved these changes

2024-01-26 09:45 UTC, merged