modification base de donne seed
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode pull request #5
Opened 2024-01-03 15:15 UTC by sebastienbaquet

2024-01-03 15:19 UTC, MaximeG971 approved these changes

2024-01-03 15:39 UTC, jujuck requested changes

2024-01-03 15:39 UTC, jujuck commented on frontend/src/main.jsx
> +  // {
A supprimer car inutile

2024-01-04 13:47 UTC, MaximeG971 submitted a review, later dismissed

2024-01-04 13:52 UTC, jujuck requested changes

2024-01-04 13:52 UTC, jujuck commented on frontend/src/pages/AdminTerminal.jsx
> +    <div>
Div inutile

2024-01-04 13:52 UTC, jujuck commented on frontend/src/pages/AdminUsers.jsx
> +    <div>
Div inutile

2024-01-04 13:52 UTC, jujuck commented on frontend/src/pages/AdminCars.jsx
> +    <div>
Div inutile

2024-01-04 13:52 UTC, jujuck commented on frontend/src/App.jsx
>      <div>
Div inutile

2024-01-04 15:05 UTC, MaximeG971 approved these changes

2024-01-04 15:19 UTC, merged