Geo location feature
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode pull request #8
Opened 2024-01-04 15:43 UTC by MaximeG971

2024-01-04 15:48 UTC, sebastienbaquet approved these changes

2024-01-04 15:48 UTC, sebastienbaquet submitted a review, later dismissed

2024-01-04 16:03 UTC, jujuck requested changes

2024-01-04 16:03 UTC, jujuck commented on frontend/src/components/Map/Map.jsx
> +/* eslint-disable no-alert */
WHAT !!! pas d'alert; utilise un plugin de type toastify

2024-01-04 16:03 UTC, jujuck commented on frontend/src/components/Map/Map.jsx
> +      alert(location.error.message);
Pas d'alert

2024-01-04 16:03 UTC, jujuck commented on frontend/src/components/Map/Map.jsx
> +      alert("Erreur inconnue");
Pas d'alert

2024-01-05 09:14 UTC, vinz-DY commented on frontend/src/components/Map/Map.jsx
> +      alert("Erreur inconnue");
ok toastify plus d alerte

2024-01-05 09:17 UTC, vinz-DY submitted a review, later dismissed

2024-01-05 09:35 UTC, jujuck requested changes

2024-01-05 09:35 UTC, jujuck commented on frontend/src/components/Map/Map.jsx
> +import PropTypes from "prop-types";
Réorganise les imports

2024-01-05 09:35 UTC, jujuck commented on frontend/src/components/Map/Map.jsx
> +    <div className="Map">
Pas de majuscule sur les class CSS

2024-01-05 09:36 UTC, jujuck approved these changes

2024-01-05 09:37 UTC, merged