ajout de menu card accéé a la page map et css
WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-GeoCode pull request #9
Opened 2024-01-04 15:48 UTC by vinz-DY

2024-01-04 15:51 UTC, MaximeG971 submitted a review, later dismissed

2024-01-04 15:59 UTC, jujuck requested changes

2024-01-04 15:59 UTC, jujuck commented on frontend/src/components/menuCard.css
> +.MenuMapDesc {
Je crois que votre convention de nommage de class Css est en minuscule

2024-01-04 15:59 UTC, jujuck commented on frontend/src/components/menuCard.css
> +.MenuMapTitle {
Idem

2024-01-04 15:59 UTC, jujuck commented on frontend/src/components/MenuCard.jsx
> +        <h2 className="MenuMapTitle">Trouvez</h2>
Majuscule au CSS !!!

2024-01-04 15:59 UTC, jujuck commented on frontend/src/components/MenuCard.jsx
> +          <p className="MenuMapDesc">la borne la plus proche</p>
Idem

2024-01-04 16:06 UTC, MaximeG971 approved these changes

2024-01-05 07:58 UTC, jujuck approved these changes

2024-01-05 07:58 UTC, merged